map_type: costmap

obstacle_range: 1.0 # 2.0
raytrace_range: 2.0 # 3.0

# some filter settings here
transform_tolerance: 0.2 # 0.0
min_particles: 5000
max_particles: 50000
update_min_d: 0.1


robot_radius: 0.3 # 0.0
inflation_radius: 0.5 # 0.0
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /localization/laser/scan, marking: true, clearing: true}
laser_max_beams: 100